### ISSUE TITLE
Failed to connect to GCP Cluster after switching from OpenLens

### ISSUE THREAD

**Issue by Torjas** [freelensapp/freelens#208]
**Describe the bug**
I used OpenLens before. I switched to Freelens and selected a Cluster in the Catalog that is in Google Cloud Platform.

This is the output shown on the loading screen:

```
Starting connection ...

Authentication proxy started

Refreshing connection status ...

Failed to get /version for clusterId=12345678901234567890: Internal Server Error

E0304 16:42:11.173463 22628 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable gke-gcloud-auth-plugin.exe not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```

I have tried to install the `gke-gcloud-auth-plugin` by running `gcloud components install gke-gcloud-auth-plugin` but it seems i already had this installed.

**To Reproduce**
1.Open Freelens
2. Got to Cluster Catalog
3. Select Cluster that is in GCP
5. See error
6. 
**Expected behavior**
The Cluster view loads and I can view and use it.

**Screenshots**

![Image](https://github.com/user-attachments/assets/bf1cdf34-586d-4292-a650-6adf4eed78d2)

**Environment (please complete the following information):**
- Freelens Version: 1.0.0
- OS: Windows 10
- Installation method: [e.g. snap or AppImage in Linux]

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```yml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [...]
    server: https://ip
  name: cluster_on_gcp

contexts:
- context:
    cluster: cluster_on_gcp
    user: cluster_on_gcp
  name: cluster_on_gcp

current-context: default
kind: Config
preferences: {}
users:
- name: cluster_on_gcp
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin.exe
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true

```

**Additional context**
