### ISSUE TITLE
Add support for native VictoriaMetrics

### ISSUE THREAD

**Issue by lucsoft** [freelensapp/freelens#524]
### What would you like to be added?

installing the VictoriaMetricStack should make the metrics work out of the box

### Why is this needed?

Making VictoraMetrics first class support will remove manual configuration for support (updating endpoint and changing labels for the hardcoded metrics renderer

**Comment by delaskoff** [comment]
@idogada-akamai this is how I did this for vmsingle

<img width="694" height="354" alt="Image" src="https://github.com/user-attachments/assets/bcba19ab-9604-4c4f-be2a-57c838487ab4" />

**Comment by delaskoff** [comment]
@robertobandini I think both vmsingle and vmcluster options should be supported and auto-discovered
For the cluster option vmselect component is used for the reading

**Comment by robertobandini** [comment]
If it's already compatible, we can specify it in the options and add the necessary parts to the auto discovered section. Otherwise, everything needed for full compatibility will need to be created, which is another effort.
If anyone wants to contribute and do their PR on this, please let us know.

**Comment by lucsoft** [comment]
Last time I checked not all metrics could be resolved so some labels where wrong

**Comment by delaskoff** [comment]
Hi @idogada-akamai 
Yes, you're right, you can only query vmselect/vmsingle. For the remote storage I believe you can also query it but you have to expose vmselect/vmsingle endpoint

**Comment by robertobandini** [comment]
Thank you all guys, I personally take a note about the fact that this one and https://github.com/freelensapp/freelens/issues/466 could be candidates for a future bounty if no one is working on them, as they seem to be highly sought after by the community (and I agree).

**Comment by rpardini** [comment]
I've tried implementing a VictoriaMetrics auto-detection in FreeLens but failed; there's simply too many ways one can deploy VicMetrics (vmsingle/vmcluster/vm-k8s-stack, etc) and my TypeScript is rusty. 

So I took the opposite approach: add a shim to VictoriaMetrics (abusing its own `vmauth` component) in such a way that is it correctly detected by FreeLens (which looks for `operated-prometheus` label, and sends requests directly at the HTTP root):

This goes into your values.yaml for `victoria-metrics-k8s-stack` Helm Chart deployment (adapt values to your scenario):

```yaml
# ---------------------------------------------------------------------------------------------------
# FreeLens Prometheus auto-detection shim.
# Lens's "operator" provider auto-detects the first Service labelled `operated-prometheus: "true"`
# (the label kube-prometheus-stack's `prometheus-operated` Service used to carry) and queries its
# ports[0].port at the ROOT Prometheus API (/api/v1/query_range). vmselect only serves that API under
# the tenant path /select/0/prometheus/, so we run a tiny vmauth that rewrites root -> tenant path,
# and put the detection label on _its_ Service. Query params/paths verified against vmauth v1.148.0.
extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata: { name: freelens-prometheus-shim, namespace: monitoring, labels: { app.kubernetes.io/name: freelens-prometheus-shim } }
    data:
      auth.yml: |
        # Any request path is appended to url_prefix -> vmselect's Prometheus query API (tenant 0).
        # --> Adapt the service name below to your reality (vmcluster/vmsingle, release name, etc).
        unauthorized_user:
          url_prefix: "http://vmselect-victoria-metrics-k8s-stack-vmstack:8481/select/0/prometheus/"
  - apiVersion: apps/v1
    kind: Deployment
    metadata: { name: freelens-prometheus-shim, namespace: monitoring, labels: { app.kubernetes.io/name: freelens-prometheus-shim } }
    spec:
      replicas: 1
      selector: { matchLabels: { app.kubernetes.io/name: freelens-prometheus-shim } }
      template:
        metadata:
          labels: { app.kubernetes.io/name: freelens-prometheus-shim }
          annotations: { checksum/config: "vmselect-tenant0-v2" } # bump to force restart on config change
        spec:
          containers:
            - name: vmauth
              image: victoriametrics/vmauth:v1.148.0 # in lockstep with the stack appVersion
              args: [ "-auth.config=/config/auth.yml", "-httpListenAddr=:8427" ]
              ports: [ { name: http, containerPort: 8427 } ]
              volumeMounts: [ { name: config, mountPath: /config, readOnly: true } ]
              readinessProbe: { tcpSocket: { port: 8427 }, initialDelaySeconds: 3 }
              resources: { requests: { cpu: 10m, memory: 32Mi }, limits: { memory: 128Mi } }
          volumes: [ { name: config, configMap: { name: freelens-prometheus-shim } } ]
  - apiVersion: v1
    kind: Service
    metadata:
      name: freelens-prometheus-shim
      namespace: monitoring
      labels:
        app.kubernetes.io/name: freelens-prometheus-shim
        operated-prometheus: "true" # <-- what FreeLens "operator" provider auto-detects
    spec:
      selector: { app.kubernetes.io/name: freelens-prometheus-shim }
      ports: [ { name: http, port: 8427, targetPort: 8427, protocol: TCP } ]
```
