### ISSUE TITLE
Add setting for accent color

### ISSUE THREAD

**Issue by Cenness** [freelensapp/freelens#550]
### What would you like to be added?

Please add an option to choose accent color. Both global and per cluster.  
If user-defined value for cluster is too hard, an option to take that accent color from generated cluster avatar/logo would be good too.
No need for color picker, just text field with hex value would be enough.

### Why is this needed?

Teal is decent, but it clashes with my os theme. And I guess easier at a glance cluster differentiation would be nice.

**Comment by robertobandini** [comment]
Nice idea!

**Comment by Cenness** [comment]
Turns out you can store arbitrary data in a kubeconfig.  
kubectl and freelens just ignore that field:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: auth
    server: https://some-cluster-endpoint:6443
    accent-color: #123456       <-----------------------------
  name: some-cluster
contexts:
- context:
    cluster: some-cluster
    user: user
  name: some-cluster
current-context: some-cluster
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: cert
    client-key-data: key
```
