### ISSUE TITLE
YAML label "yes" parsed as boolean by UI, causes resource creation to fail

### ISSUE THREAD

**Issue by Gunjpz** [freelensapp/freelens#881]
### Describe the bug

- When creating a ConfigMap with a label value "yes" (as a string), FreeLens shows an error: `"json: cannot unmarshal bool into Go struct field ObjectMeta.metadata.labels of type string"`
- Even though the label is quoted (`"yes"`), it is being interpreted as a boolean, which is invalid for Kubernetes labels.

### Reproduction steps

1. Open ConfigMap creation in FreeLens
2. Use the following YAML:
    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: configmap-test-001
      labels:
        allow-custom-indices: "yes"
    data:
      foo: bar
    ```
3. Click "Create"  
4. See the error

![Image](https://github.com/user-attachments/assets/948bf808-b012-4d03-97d0-106e93cd25af)

### Expected behavior

The label value `"yes"` (as a string) should be accepted as a valid label value. The resource should be created without error.

### Freelens version

1.3.2

### Operating system type and version

Windows 11

### Installation method

EXE

### Additional context

- It seems the YAML parser or JSON converter is interpreting `"yes"` as a boolean.  
- This does not happen with `"enabled"` or `"allowed"` as the value.  
- Applying the same YAML via kubectl works fine.

**Workaround**
Change label value to a string like `"enabled"`, and it works like a charm.
